language: python
env:
  global:
  - HUGO_VERSION="0.53"
before_install:
- openssl aes-256-cbc -K $encrypted_c4f15883beb6_key -iv $encrypted_c4f15883beb6_iv -in deploy-clusterfrak-dynamics.github.io.key.enc -out deploy-clusterfrak-dynamics.github.io.key -d
install:
- pip install ghp-import
script:
- wget -qO- "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz"
  | tar xvz
- ls
- "./hugo"
- ghp-import public
branches:
  only:
  - master
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 deploy-clusterfrak-dynamics.github.io.key
- ssh-add deploy-clusterfrak-dynamics.github.io.key
- git push -f git@github.com:clusterfrak-dynamics/clusterfrak-dynamics.github.io.git gh-pages:master
