baseurl                 = "https://clusterfrak-dynamics.github.io/"               # Your domain name. Must end with "/"
languageCode            = "en-us"
defaultContentLanguage  = "en"
isMultilingual          = false
title                   = "/clusterfrak-dynamics"
theme                   = "sam"
pygmentsStyle           = "monokai"                     # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
googleAnalytics         = "UA-85614178-2"             # Tracking code, eg. "UA-111111111-1"

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "sam.ico"
    homepage            = "main"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = false                          # Allow links to the full size images
    smallPreviewImages   = true                         # Show small images from the subfolder instead of the big versions in the gallery
                                                         # Note: This will only become active if clickablePhotos is also true.
    smallImagesSubfolder = "small/"                      # The subfolder for the small versions of the images under the gallery (with trailing slash)
                                                         # For each image the small version has to have the same filename as the big version.
    footerText          = "© 2018. Kevin Lefevre. [Some Rights Reserved](https://creativecommons.org/licenses/by-sa/4.0/)."

# Metadata
    description         = "clusterfrak-dynamics"            # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "tn.png"                     # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "https://github.com/clusterfrak-dynamics"
    text = "/clusterfrak-dynamics"

[[params.mainMenu]]
    link = "/symplegma"
    text = "\n/symplegma"

[[params.mainMenu]]
    link = "/teks"
    text = "    /teks"
